Prevent crash due to `class` being `null`
When search work Element in launcher and about to hold it to display
*App info*.

## Report Info

**User Action**: `plugin execution command`
**Sender**: `TermuxApiReceiver`
**Report Timestamp**: `2026-03-17 15:13:54.252 UTC`
##

## Termux:API Error

```
Error in TermuxApiReceiver:
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
	at com.termux.api.apis.AccessibilityAPI.dumpNodeAuxiliary(AccessibilityAPI.java:255)
	at com.termux.api.apis.AccessibilityAPI.dumpNodeAuxiliary(AccessibilityAPI.java:290)
	at com.termux.api.apis.AccessibilityAPI.dumpNodeAuxiliary(AccessibilityAPI.java:290)
	at com.termux.api.apis.AccessibilityAPI.dumpNodeAuxiliary(AccessibilityAPI.java:290)
	at com.termux.api.apis.AccessibilityAPI.dumpNodeAuxiliary(AccessibilityAPI.java:290)
	at com.termux.api.apis.AccessibilityAPI.dumpAuxiliary(AccessibilityAPI.java:212)
	at com.termux.api.apis.AccessibilityAPI.dump(AccessibilityAPI.java:188)
	at com.termux.api.apis.AccessibilityAPI.onReceive(AccessibilityAPI.java:130)
	at com.termux.api.TermuxApiReceiver.doWork(TermuxApiReceiver.java:90)
	at com.termux.api.TermuxApiReceiver.onReceive(TermuxApiReceiver.java:67)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:5301)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2715)
	at android.os.Handler.dispatchMessage(Handler.java:132)
	at android.os.Looper.dispatchMessage(Looper.java:333)
	at android.os.Looper.loopOnce(Looper.java:263)
	at android.os.Looper.loop(Looper.java:367)
	at android.app.ActivityThread.main(ActivityThread.java:9287)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:566)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:929)

```

## Termux:API App Info (Current)

**APP_NAME**: `Termux:API`
**PACKAGE_NAME**: `com.termux.api`
**VERSION_NAME**: `0.53.0`
**VERSION_CODE**: `1002`
**UID**: `10190`
**TARGET_SDK**: `28`
**IS_DEBUGGABLE_BUILD**: `true`
**SE_PROCESS_CONTEXT**: `u:r:untrusted_app_27:s0:c190,c256,c512,c768`
**SE_FILE_CONTEXT**: `u:object_r:app_data_file:s0:c190,c256,c512,c768`
**SE_INFO**: `default:targetSdkVersion=28:complete`
**APK_RELEASE**: `Github`
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`
##

## Termux App Info

**APP_NAME**: `Termux`
**PACKAGE_NAME**: `com.termux`
**VERSION_NAME**: `0.118.0`
**VERSION_CODE**: `118`
**UID**: `10190`
**TARGET_SDK**: `28`
**IS_DEBUGGABLE_BUILD**: `true`
**SE_PROCESS_CONTEXT**: `u:r:untrusted_app_27:s0:c190,c256,c512,c768`
**SE_FILE_CONTEXT**: `u:object_r:app_data_file:s0:c190,c256,c512,c768`
**SE_INFO**: `default:targetSdkVersion=28:complete`
**TERMUX_APP_PACKAGE_MANAGER**: -
**TERMUX_APP_PACKAGE_VARIANT**: -
**APK_RELEASE**: `Github`
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`
##

## Device Info

### Software

**OS_VERSION**: `4.19.325-cip128-st12-perf-g6ec2fe2d2a1f`
**SDK_INT**: `36`
**RELEASE**: `16`
**ID**: `BP4A.251205.006`
**DISPLAY**: `BP4A.251205.006`
**INCREMENTAL**: `5ddb16882c`
**SECURITY_PATCH**: `2026-02-01`
**IS_TREBLE_ENABLED**: `true`
**TYPE**: `userdebug`
**TAGS**: `release-keys`
**MAX_PHANTOM_PROCESSES**: - (*Requires `DUMP` and `PACKAGE_USAGE_STATS` permission*)
**MONITOR_PHANTOM_PROCS**: `false`
**DEVICE_CONFIG_SYNC_DISABLED**: -

### Hardware

**MANUFACTURER**: `Fairphone`
**BRAND**: `Fairphone`
**MODEL**: `FP4`
**PRODUCT**: `FP4eea`
**BOARD**: `FP4`
**HARDWARE**: `qcom`
**DEVICE**: `FP4`
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`
##